### ISSUE TITLE
verify_payment.php, success.php

### ISSUE THREAD

**Issue by mhaken** [hariom-kesharwani/PHP-SUMUP-PAYMENT-GATEWAY-INTEGRATION#1]
Hi, can you share verify_payment.php and success.php? Thanks.

**Comment by hariom-kumar-bs** [comment]
Hi Mhaken, I will be update you soon.

**Comment by hariom-kesharwani** [comment]
Hi Mhaken,
"verify_payment.php" and "success.php"  are the files are not related payment gateway integration. These files path you can use to redirect to success page once payment done. You can write the logic what ever you want in payment success.
